// scripts/deploy.js
// Run: npx hardhat run scripts/deploy.js --network sepolia

import hre from "hardhat";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const { ethers } = hre;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  const [deployer] = await ethers.getSigners();
  const TREASURY = "0xE2E9E60bc81D0695e74045bfc841eD2cA7a81e9F"; // your wallet — receives 2.5% fees
  console.log("Deploying DecentCrowd with account:", deployer.address);
  console.log("Treasury (fee recipient):", TREASURY);
  console.log("Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH");

  // Deploy contract
  const DecentCrowd = await ethers.getContractFactory("DecentCrowd");
  const contract = await DecentCrowd.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("\n✅ DecentCrowd deployed to:", address);
  console.log("🔗 Sepolia Etherscan:", `https://sepolia.etherscan.io/address/${address}`);

  // Seed 6 demo campaigns matching the app's hardcoded data
  console.log("\nSeeding demo campaigns...");

  const campaigns = [
    {
      title: "Lagos Solar Grid — Community Energy Access",
      category: "Energy",
      country: "Nigeria",
      image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80",
      goalEth: "0.5",
      days: 30,
      milestones: ["Purchase solar panels and inverters", "Install micro-grid infrastructure", "Connect 2,400 households"],
      percents: [30, 40, 30],
    },
    {
      title: "Accra Cooperative Farm — Direct Market Access",
      category: "Agriculture",
      country: "Ghana",
      image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=80",
      goalEth: "0.3",
      days: 45,
      milestones: ["Build cold storage facility", "Deploy mobile logistics platform"],
      percents: [50, 50],
    },
    {
      title: "Dakar Mobile Clinic — Maternal Health Initiative",
      category: "Health",
      country: "Senegal",
      image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80",
      goalEth: "0.4",
      days: 20,
      milestones: ["Procure 5 mobile health units", "Train medical staff", "Deploy to remote villages"],
      percents: [40, 20, 40],
    },
    {
      title: "Harare Tech Hub — Youth Digital Skills",
      category: "Education",
      country: "Zimbabwe",
      image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
      goalEth: "0.2",
      days: 60,
      milestones: ["Renovate building and install equipment", "Run first cohort of 100 students"],
      percents: [60, 40],
    },
    {
      title: "Nairobi Creative Arts Centre",
      category: "Arts",
      country: "Kenya",
      image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80",
      goalEth: "0.25",
      days: 40,
      milestones: ["Secure venue and equipment", "Launch first exhibition", "Establish residency programme"],
      percents: [40, 30, 30],
    },
    {
      title: "Conakry Clean Water Initiative",
      category: "Health",
      country: "Guinea",
      image: "https://images.unsplash.com/photo-1594498653385-d5172c532c00?w=600&q=80",
      goalEth: "0.35",
      days: 50,
      milestones: ["Install water filtration systems", "Build distribution network", "Train local operators"],
      percents: [35, 40, 25],
    },
  ];

  const seeded = [];
  for (const c of campaigns) {
    const tx = await contract.createCampaign(
      c.title, c.category, c.country, c.image,
      ethers.parseEther(c.goalEth),
      c.days,
      c.milestones,
      c.percents
    );
    const receipt = await tx.wait();
    // Get campaign ID from event
    const event = receipt.logs.find(l => {
      try { return contract.interface.parseLog(l).name === "CampaignCreated"; } catch { return false; }
    });
    const parsed = contract.interface.parseLog(event);
    const id = parsed.args[0].toString();
    console.log(`  ✓ Campaign ${id}: ${c.title.substring(0, 40)}...`);
    seeded.push({ id, title: c.title });
  }

  // Write contract address to src/lib/contract.js for the frontend
  const contractConfig = `// Auto-generated by deploy.js — do not edit manually
export const CONTRACT_ADDRESS = "${address}";
export const CHAIN_ID = 11155111; // Sepolia
export const CHAIN_NAME = "Sepolia";
export const RPC_URL = "https://rpc.sepolia.org";
export const EXPLORER = "https://sepolia.etherscan.io";
`;

  const outPath = path.join(__dirname, "../src/lib/contract.js");
  fs.writeFileSync(outPath, contractConfig);
  console.log(`\n✅ Contract address written to src/lib/contract.js`);
  console.log("\n🎉 Done! Copy the contract address into your .env if needed:");
  console.log(`   CONTRACT_ADDRESS=${address}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
